import { defineConfig } from 'vite';
import path from 'path';
import { copyFileSync, mkdirSync, readdirSync, readFileSync, writeFileSync, existsSync } from 'fs';
import dts from 'vite-plugin-dts';

function copyDir(src, dest) {
  mkdirSync(dest, { recursive: true });
  const entries = readdirSync(src, { withFileTypes: true });

  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);

    if (entry.isDirectory()) {
      copyDir(srcPath, destPath);
    } else if (entry.name.endsWith('.svelte')) {
      // Copy Svelte files and update their TS imports to JS
      let content = readFileSync(srcPath, 'utf-8');
      
      // Replace .ts imports with .js (but not .d.ts)
      content = content.replace(
        /from\s+(['"])(.+?)\.ts\1/g,
        (match, quote, path) => `from ${quote}${path}.js${quote}`
      );
      content = content.replace(
        /import\s+(['"])(.+?)\.ts\1/g,
        (match, quote, path) => `import ${quote}${path}.js${quote}`
      );
      
      writeFileSync(destPath, content, 'utf-8');
    } else if (entry.name.endsWith('.js')) {
      // Copy JS files as-is
      copyFileSync(srcPath, destPath);
    }
    // Skip .ts files - they will be transpiled by Vite
    // Skip .d.ts files - they will be generated by dts plugin
  }
}

function generateAmbientDts(distDir) {
  const entries = readdirSync(distDir, { withFileTypes: true, recursive: true });
  const declarations = [];

  for (const entry of entries) {
    if (entry.name.endsWith('.d.ts') && entry.name !== 'ambient.d.ts' && entry.name !== 'index.d.ts') {
      const fullPath = path.join(entry.path || entry.parentPath || distDir, entry.name);
      const relativePath = path.relative(distDir, fullPath);
      const moduleName = './' + relativePath.replace(/\.d\.ts$/, '').replace(/\\/g, '/');
      
      declarations.push(`declare module '${moduleName}' {`);
      const content = readFileSync(fullPath, 'utf-8');
      declarations.push(`  ${content.split('\n').join('\n  ')}`);
      declarations.push(`}\n`);
    }
  }

  if (declarations.length > 0) {
    const ambientPath = path.join(distDir, 'ambient.d.ts');
    writeFileSync(ambientPath, declarations.join('\n'), 'utf-8');
    console.log('Generated ambient.d.ts');
  }
}

export default defineConfig({
  plugins: [
    {
      name: 'copy-source-files',
      // Run BEFORE dts plugin by using closeBundle instead of writeBundle
      closeBundle() {
        copyDir('src', 'dist');
      }
    },
    dts({
      include: ['src/**/*.ts'],
      exclude: ['**/*.svelte'],
      outDir: 'dist',
      copyDtsFiles: true,
      rollupTypes: false, // Keep individual .d.ts files
      afterBuild: () => {
        console.log('TypeScript declarations generated');
        
        // Generate ambient.d.ts from all .d.ts files
        generateAmbientDts('dist');
        
        // Add triple-slash reference to index.d.ts if it exists
        const indexDtsPath = path.resolve(__dirname, 'dist/index.d.ts');
        if (existsSync(indexDtsPath)) {
          let content = readFileSync(indexDtsPath, 'utf-8');
          
          // Check if the reference directive already exists
          if (!content.includes('/// <reference types="./ambient"')) {
            // Add the reference directive at the top
            content = `/// <reference types="./ambient" />\n\n${content}`;
            writeFileSync(indexDtsPath, content, 'utf-8');
            console.log('Added ambient type reference to index.d.ts');
          }
        }
      }
    })
  ],
  build: {
    lib: {
      entry: path.resolve(__dirname, 'src/index.ts'),
      formats: ['es']
    },
    rollupOptions: {
      treeshake: false, // Disable treeshaking to preserve modules used in Svelte components
      external: (id) => {
        // Externalize svelte and .svelte files
        return id === 'svelte' || 
               id === 'svelte/legacy' || 
               id === 'svelte/internal' || 
               id.endsWith('.svelte');
      },
      output: {
        entryFileNames: '[name].js',
        chunkFileNames: '[name].js',
        preserveModules: true,
        preserveModulesRoot: 'src'
      },
      // Custom plugin to fix imports
      plugins: [
        {
          name: 'fix-svelte-imports',
          resolveId(source, importer) {
            // If importing a .svelte file, make it relative
            if (source.endsWith('.svelte')) {
              // Extract just the filename
              const filename = source.split('/').pop() || source.split('\\').pop();
              return { id: './' + filename, external: true };
            }
            return null;
          }
        }
      ]
    },
    outDir: 'dist',
    emptyOutDir: true
  }
});